<a href="https://colab.research.google.com/github/rugihub/deep_learning_2018-19/blob/master/%5Bseminar%5Dpytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>

<h3 style="text-align: center;"><b>"Глубокое обучение". Продвинутый поток</b></h3>

<h2 style="text-align: center;"><b>Семинар 6. Основы библиотеки Pythorch </b></h2>


<h2 style="text-align: center;"><b>PyTorch basics: syntax, torch.cuda and torch.autograd</b></h2>

<p style="align: center;"><img src="https://upload.wikimedia.org/wikipedia/commons/9/96/Pytorch_logo.png" width=400 height=100></p>

Hi! In this notebook we will cover the basics of the **PyTorch deep learning framework**. 

<h3 style="text-align: center;"><b>Intro</b></h3>

**Frameworks** are the specific code libraries with their own internal structure and pipelines.

There are many deep learning frameworks nowadays (02/2019). The difference between them is in the internal computation principles. For example, in **[Caffe](http://caffe.berkeleyvision.org/)** and **[Caffe2](https://caffe2.ai/)** you write the code using some "ready blocks" (just like the $LEGO^{TM}$ :). In **[TensorFlow](https://www.tensorflow.org/)** and **[Theano](http://deeplearning.net/software/theano/)** you declare the computation graph at first, then compile it and use it for inference/training (`tf.session()`). By the way, now TensorFlow (since v1.10) has the [Eager Execution](https://www.tensorflow.org/guide/eager), which can be handy for fast prototyping and debugging. **[Keras](https://keras.io/)** is a very popular and useful DL framework that allows to create networks fast and has many demanding features. 

<p style="align: center;"><img src="https://habrastorage.org/web/e3e/c3e/b78/e3ec3eb78d714a7993a6b922911c0866.png" width=500 height=500></p>  
<p style="text-align: center;"><i>Image credit: https://habr.com/post/334380/</i><p>

We will use PyTorch bacause it's been actively developed and supported by the community and [Facebook AI Research](https://research.fb.com/category/facebook-ai-research/).

<h3 style="text-align: center;"><b>Installation</b></h3>

The detailed instruction on how to install PyTorch you can find on the [official PyTorch website](https://pytorch.org/).

<h3 style="text-align: center;">Syntax<b></b></h3>

In [0]:
import torch

Some facts about PyTorch:  
- dynamic computation graph
- handy `torch.nn` and `torchvision` modules for fast neural network prototyping
- even faster than TensorFlow on some tasks
- allows to use GPU easily

If PyTorch was a formula, it would be:  

$$PyTorch = NumPy + CUDA + Autograd$$

(CUDA - [wiki](https://en.wikipedia.org/wiki/CUDA))

Let's see how we can use PyTorch to operate with vectors and tensors.  

Recall that **a tensor** is a multidimensional vector, e.g. :  

`x = np.array([1,2,3])` -- a vector = a tensor with 1 dimension (to be more precise: `(1,)`)  
`y = np.array([[1, 2, 3], [4, 5, 6]])` -- a matrix = a tensor with 2 dimensions (`(2, 3)` in this case)  
`z = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],  
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]],  
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])` -- "a cube" (3, 3, 3) = a tensor with 3 dimensions (`(3, 3, 3)` in this case)

One real example of 3-dimensional tensor is **an image**, it has 3 dimensions: `height`, `width` and the `channel depth` (= 3 for color images, 1 for a greyscale). You can think of it as of parallelepiped consisting of the real numbers.

In PyTorch we will use `torch.Tensor` (`FloatTensor`, `IntTensor`, `ByteTensor`) for all the computations.

All tensor types:

In [2]:
torch.HalfTensor      # 16 бит, floating point
torch.FloatTensor     # 32 бита, floating point
torch.DoubleTensor    # 64 бита, floating point

torch.ShortTensor     # 16 бит, integer, signed
torch.IntTensor       # 32 бита, integer, signed
torch.LongTensor      # 64 бита, integer, signed

torch.CharTensor      # 8 бит, integer, signed
torch.ByteTensor      # 8 бит, integer, unsigned

torch.ByteTensor

We will use only `torch.FloatTensor()` and `torch.IntTensor()`. 

Let's begin to do something!

* Creating the tensor:

In [3]:
a = torch.FloatTensor([1, 2])
a


tensor([1., 2.])

In [0]:
a.shape

torch.Size([2])

In [4]:
b = torch.FloatTensor([[1,2,3], [4,5,6]])
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [5]:
b.shape

torch.Size([2, 3])

In [0]:
x = torch.FloatTensor(2,3,4)

In [7]:
x

tensor([[[7.4308e-38, 0.0000e+00, 7.0065e-44, 6.7262e-44],
         [6.3058e-44, 6.7262e-44, 7.4269e-44, 6.3058e-44],
         [6.8664e-44, 7.7071e-44, 1.1771e-43, 6.8664e-44]],

        [[7.0065e-44, 8.1275e-44, 7.1466e-44, 7.5670e-44],
         [8.1275e-44, 7.1466e-44, 7.0065e-44, 6.4460e-44],
         [7.1466e-44, 6.8664e-44, 7.1466e-44, 6.7262e-44]]])

In [8]:
x = torch.FloatTensor(100)
x

tensor([ 2.8371e-36,  0.0000e+00,  1.4396e-38,  0.0000e+00,  5.8154e-43,
         0.0000e+00,         nan,         nan,  4.4721e+21,  2.3079e+20,
         6.2689e+22,  4.7428e+30,  1.3563e-19,  1.3817e-19, -1.0752e+10,
        -9.9222e+10,  1.8910e+23,  7.1443e+31,  1.9603e-19,  1.8061e+28,
         7.5527e+28,  5.2839e-11,  2.7604e+20,  1.7744e+28,  2.0535e-19,
         1.3563e-19,  1.0426e-08, -2.3866e+10, -1.7558e+10,  1.8910e+23,
         7.1443e+31,  1.9603e-19,  1.8061e+28,  7.5527e+28,  5.2839e-11,
         1.1319e+21,  6.2688e+22,  4.7428e+30,  1.3563e-19,  1.6962e-07,
        -2.3866e+10, -1.7558e+10,  1.8910e+23,  7.1443e+31,  1.9603e-19,
         1.8061e+28,  4.3747e+31,  4.2964e+24,  7.1901e+28,  6.2706e+22,
         4.7428e+30,  1.3563e-19,  2.3303e-09, -6.0573e-09, -3.0816e-37,
         1.8037e+28,  6.8296e+22,  1.2690e+31,  7.0364e+22,  7.5527e+28,
         5.2839e-11,  4.1993e+12,  7.5338e+28,  1.3563e-19,  1.3563e-19,
         1.0426e-08, -2.3866e+10, -1.7558e+10,  1.2

In [0]:
x = torch.IntTensor(45, 57, 14, 2)
x.shape

torch.Size([45, 57, 14, 2])

**Note:** if you create `torch.Tensor` with the following constructor it will be filled with the "random trash numbers":

In [9]:
x = torch.IntTensor(3, 2, 4)
x

tensor([[[30034176,        0,       50,       48],
         [      45,       48,       53,       45]],

        [[      49,       55,       84,       49],
         [      50,       58,       51,       54]],

        [[      58,       53,       48,       46],
         [      48,       55,       52,       48]]], dtype=torch.int32)

Here is a way to fill a new tensor with zeroes:

In [10]:
x = torch.FloatTensor(3, 2, 4).zero_()
x

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

## Numpy -> Torch

All numpy function have its pair in torch.

https://github.com/torch/torch7/wiki/Torch-for-Numpy-users

`np.reshape()` == `torch.view()`:

In [11]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [12]:
b.view(3, 2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

**Note:** `torch.view()` creates a new tensor, one the old one remains unchanged

In [13]:
b.view(-1)

tensor([1., 2., 3., 4., 5., 6.])

In [14]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

* Change a tensor type:

In [0]:
a = torch.FloatTensor([1.5, 3.2, -7])

In [17]:
a.type_as(torch.IntTensor())

tensor([ 1,  3, -7], dtype=torch.int32)

In [18]:
a.type_as(torch.ByteTensor())

tensor([  1,   3, 249], dtype=torch.uint8)

**Note:** `.type_as()` creates a new tensor, the old one remains unchanged

In [19]:
a

tensor([ 1.5000,  3.2000, -7.0000])

* Indexing is just like in `NumPy`:

In [20]:
a = torch.FloatTensor([[100, 20, 35], [15, 163, 534], [52, 90, 66]])
a

tensor([[100.,  20.,  35.],
        [ 15., 163., 534.],
        [ 52.,  90.,  66.]])

In [21]:
a[0, 0]

tensor(100.)

In [22]:
a[0:2, 0:2]

tensor([[100.,  20.],
        [ 15., 163.]])

**Ariphmetics and boolean operations** and their analogues:  

| Operator | Analogue |
|:-:|:-:|
|`+`| `torch.add()` |
|`-`| `torch.sub()` |
|`*`| `torch.mul()` |
|`/`| `torch.div()` |

* Addition:

In [0]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [0]:
a + b

tensor([[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [200., 400., 600.]])

In [24]:
a.add(b)

tensor([[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [200., 400., 600.]])

In [25]:
b = -a
b

tensor([[  -1.,   -2.,   -3.],
        [ -10.,  -20.,  -30.],
        [-100., -200., -300.]])

In [26]:
a + b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

* Subtraction:

In [27]:
a - b

tensor([[  2.,   4.,   6.],
        [ 20.,  40.,  60.],
        [200., 400., 600.]])

In [28]:
a.sub(b)

tensor([[  2.,   4.,   6.],
        [ 20.,  40.,  60.],
        [200., 400., 600.]])

* Multiplication (elementwise):

In [29]:
a * b

tensor([[-1.0000e+00, -4.0000e+00, -9.0000e+00],
        [-1.0000e+02, -4.0000e+02, -9.0000e+02],
        [-1.0000e+04, -4.0000e+04, -9.0000e+04]])

In [0]:
a.mul(b)

tensor([[-1.0000e+00, -4.0000e+00, -9.0000e+00],
        [-1.0000e+02, -4.0000e+02, -9.0000e+02],
        [-1.0000e+04, -4.0000e+04, -9.0000e+04]])

* Division (elementwise):

In [0]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [0]:
a / b

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [ 1.,  1.,  1.]])

In [31]:
a.div(b)

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [ 1.,  1.,  1.]])

**Note:** all this operations create new tensors, the old tensors remain unchanged

In [32]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [33]:
b

tensor([[ -1.,  -2.,  -3.],
        [-10., -20., -30.],
        [100., 200., 300.]])

* Comparison operators:

In [0]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [35]:
a == b

tensor([[False, False, False],
        [False, False, False],
        [ True,  True,  True]])

In [36]:
a != b

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [False, False, False]])

In [0]:
a < b

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [37]:
a > b

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [False, False, False]])

* Using boolean mask indexing:

In [38]:
a[a > b]

tensor([ 1.,  2.,  3., 10., 20., 30.])

In [39]:
b[a == b]

tensor([100., 200., 300.])

Elementwise application of the **universal functions**:

In [0]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])

In [41]:
a.sin()

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.5440,  0.9129, -0.9880],
        [-0.5064, -0.8733, -0.9998]])

In [42]:
torch.sin(a)

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.5440,  0.9129, -0.9880],
        [-0.5064, -0.8733, -0.9998]])

In [0]:
a.tan()

tensor([[ 1.5574, -2.1850, -0.1425],
        [ 0.6484,  2.2372, -6.4053],
        [-0.5872, -1.7925, 45.2447]])

In [43]:
a.exp()

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01],
        [2.2026e+04, 4.8517e+08, 1.0686e+13],
        [       inf,        inf,        inf]])

In [44]:
a.log()

tensor([[0.0000, 0.6931, 1.0986],
        [2.3026, 2.9957, 3.4012],
        [4.6052, 5.2983, 5.7038]])

In [45]:
b = -a
b

tensor([[  -1.,   -2.,   -3.],
        [ -10.,  -20.,  -30.],
        [-100., -200., -300.]])

In [46]:
b.abs()

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

* The sum, mean, max, min:

In [47]:
a.sum()

tensor(666.)

In [48]:
a.mean()

tensor(74.)

Along axis:

In [49]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [50]:
a.sum(dim=0)

tensor([111., 222., 333.])

In [52]:
a.sum(1)

tensor([  6.,  60., 600.])

In [53]:
a.max()

tensor(300.)

In [54]:
a.max(0)

torch.return_types.max(values=tensor([100., 200., 300.]), indices=tensor([2, 2, 2]))

In [55]:
a.min()

tensor(1.)

In [56]:
a.min(0)

torch.return_types.min(values=tensor([1., 2., 3.]), indices=tensor([0, 0, 0]))

**Note:** the second tensor returned by `.max()` and `.min()` contains the indices of max/min elements along this axis. E.g. in that case `a.min()` returned `(1, 2, 3)` which are the minimum elements along 0 axis (along columns) and their indices along 0 axis are `(0, 0, 0)`.

**Matrix operations**:

* Transpose a tensor:

In [57]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [58]:
a.t()

tensor([[  1.,  10., 100.],
        [  2.,  20., 200.],
        [  3.,  30., 300.]])

It is not not the inplace operation too:

In [59]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

* Dot product of vectors:

In [0]:
a = torch.FloatTensor([1, 2, 3, 4, 5, 6])
b = torch.FloatTensor([-1, -2, -4, -6, -8, -10])

In [61]:
a.dot(b)

tensor(-141.)

In [62]:
a.shape, b.shape

(torch.Size([6]), torch.Size([6]))

In [63]:
a @ b

tensor(-141.)

In [64]:
type(a)

torch.Tensor

In [0]:
type(b)

torch.Tensor

In [65]:
type(a @ b)

torch.Tensor

* Matrix product:

In [0]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [67]:
a.mm(b)

tensor([[  279.,   558.,   837.],
        [ 2790.,  5580.,  8370.],
        [27900., 55800., 83700.]])

In [68]:
a @ b

tensor([[  279.,   558.,   837.],
        [ 2790.,  5580.,  8370.],
        [27900., 55800., 83700.]])

Remain unchanged:

In [69]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [70]:
b

tensor([[ -1.,  -2.,  -3.],
        [-10., -20., -30.],
        [100., 200., 300.]])

In [0]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1], [-10], [100]])

In [72]:
print(a.shape, b.shape)

torch.Size([3, 3]) torch.Size([3, 1])


In [73]:
a @ b

tensor([[  279.],
        [ 2790.],
        [27900.]])

If we unroll the tensor `b` in an array (`torch.view(-1)`) the multiplication would be like with the column:

In [74]:
b

tensor([[ -1.],
        [-10.],
        [100.]])

In [0]:
b.view(-1)

In [76]:
a @ b.view(-1)

tensor([  279.,  2790., 27900.])

In [77]:
a.mv(b.view(-1))

tensor([  279.,  2790., 27900.])

**From NumPu to PyTorch conversion**:

In [78]:
import numpy as np

a = np.random.rand(3, 3)
a

array([[0.06910948, 0.04894273, 0.9335921 ],
       [0.83714388, 0.06317969, 0.01598006],
       [0.13527366, 0.60407815, 0.88308182]])

In [79]:
b = torch.from_numpy(a)
b

tensor([[0.0691, 0.0489, 0.9336],
        [0.8371, 0.0632, 0.0160],
        [0.1353, 0.6041, 0.8831]], dtype=torch.float64)

**NOTE!** `a` and `b` have the same data storage, so the changes in one tensor will lead to the changes in another:

In [80]:
b -= b
b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [81]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**From PyTorch to NumPy conversion:**

In [82]:
a = torch.FloatTensor(2, 3, 4)
a

tensor([[[7.4310e-38, 0.0000e+00, 7.0065e-44, 6.7262e-44],
         [6.3058e-44, 6.7262e-44, 7.4269e-44, 6.3058e-44],
         [6.8664e-44, 7.7071e-44, 1.1771e-43, 6.8664e-44]],

        [[7.0065e-44, 8.1275e-44, 7.2868e-44, 7.4269e-44],
         [8.1275e-44, 7.0065e-44, 7.5670e-44, 6.4460e-44],
         [7.2868e-44, 7.7071e-44, 7.2868e-44, 7.1466e-44]]])

In [83]:
type(a)

torch.Tensor

In [84]:
x = a.numpy()
x

array([[[7.4309983e-38, 0.0000000e+00, 7.0064923e-44, 6.7262326e-44],
        [6.3058431e-44, 6.7262326e-44, 7.4268819e-44, 6.3058431e-44],
        [6.8663625e-44, 7.7071416e-44, 1.1770907e-43, 6.8663625e-44]],

       [[7.0064923e-44, 8.1275311e-44, 7.2867520e-44, 7.4268819e-44],
        [8.1275311e-44, 7.0064923e-44, 7.5670117e-44, 6.4459729e-44],
        [7.2867520e-44, 7.7071416e-44, 7.2867520e-44, 7.1466222e-44]]],
      dtype=float32)

In [85]:
x.shape

(2, 3, 4)

In [87]:
type(x)

numpy.ndarray

In [0]:
x -= x

In [89]:
a

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

Let's write the `forward_pass(X, w)` ($w_0$ is a part of the $w$) for a single neuron (activation = sigmoid) using PyTorch:

In [0]:
def forward_pass(X, w):
    return torch.sigmoid(X @ w)

In [91]:
X = torch.FloatTensor([[-5, 5], [2, 3], [1, -1]])
w = torch.FloatTensor([[-0.5], [2.5]])
result = forward_pass(X, w)
print('result: {}'.format(result))

result: tensor([[1.0000],
        [0.9985],
        [0.0474]])


<h3 style="text-align: center;"><a href="https://ru.wikipedia.org/wiki/CUDA">CUDA</a></h3>

[CUDA documentation](https://docs.nvidia.com/cuda/)

We can use both CPU (Central Processing Unit) and GPU (Graphical Processing Unit) to make the computations with PyTorch. We can switch between them easily, this is one of the most important things in PyTorch framework.

In [92]:
x = torch.FloatTensor(1024, 1024).uniform_()
x

tensor([[0.8466, 0.3820, 0.9868,  ..., 0.1003, 0.6803, 0.3629],
        [0.9815, 0.3738, 0.9910,  ..., 0.7640, 0.6732, 0.5278],
        [0.6121, 0.9952, 0.1886,  ..., 0.6566, 0.1483, 0.7380],
        ...,
        [0.3556, 0.7658, 0.0643,  ..., 0.5383, 0.4563, 0.7976],
        [0.3461, 0.7474, 0.6738,  ..., 0.7413, 0.8677, 0.5166],
        [0.6616, 0.4325, 0.3762,  ..., 0.8478, 0.7001, 0.0740]])

In [93]:
x.is_cuda

False

Place a tensor on GPU:

In [0]:
x = x.cuda()

In [95]:
x

tensor([[0.8466, 0.3820, 0.9868,  ..., 0.1003, 0.6803, 0.3629],
        [0.9815, 0.3738, 0.9910,  ..., 0.7640, 0.6732, 0.5278],
        [0.6121, 0.9952, 0.1886,  ..., 0.6566, 0.1483, 0.7380],
        ...,
        [0.3556, 0.7658, 0.0643,  ..., 0.5383, 0.4563, 0.7976],
        [0.3461, 0.7474, 0.6738,  ..., 0.7413, 0.8677, 0.5166],
        [0.6616, 0.4325, 0.3762,  ..., 0.8478, 0.7001, 0.0740]],
       device='cuda:0')

In [96]:
device = torch.device("cuda:0")
x = x.to(device)
x

tensor([[0.8466, 0.3820, 0.9868,  ..., 0.1003, 0.6803, 0.3629],
        [0.9815, 0.3738, 0.9910,  ..., 0.7640, 0.6732, 0.5278],
        [0.6121, 0.9952, 0.1886,  ..., 0.6566, 0.1483, 0.7380],
        ...,
        [0.3556, 0.7658, 0.0643,  ..., 0.5383, 0.4563, 0.7976],
        [0.3461, 0.7474, 0.6738,  ..., 0.7413, 0.8677, 0.5166],
        [0.6616, 0.4325, 0.3762,  ..., 0.8478, 0.7001, 0.0740]],
       device='cuda:0')

Let's multiply two tensors on GPU and then move the result on the CPU:

In [0]:
a = torch.FloatTensor(10000, 10000).uniform_()
b = torch.FloatTensor(10000, 10000).uniform_()
c = a.cuda().mul(b.cuda()).cpu()

In [98]:
c

tensor([[0.1197, 0.0777, 0.4021,  ..., 0.0233, 0.4609, 0.3579],
        [0.2560, 0.4455, 0.1819,  ..., 0.4303, 0.8230, 0.2530],
        [0.6802, 0.4752, 0.3406,  ..., 0.3460, 0.0496, 0.7174],
        ...,
        [0.4158, 0.1121, 0.0638,  ..., 0.1643, 0.0224, 0.3206],
        [0.1772, 0.3648, 0.6455,  ..., 0.2230, 0.3517, 0.2654],
        [0.2738, 0.0034, 0.5410,  ..., 0.4092, 0.0055, 0.0589]])

In [99]:
a

tensor([[0.9255, 0.1287, 0.7739,  ..., 0.1078, 0.4999, 0.4378],
        [0.3855, 0.8657, 0.7349,  ..., 0.5971, 0.9463, 0.3013],
        [0.9472, 0.5625, 0.7611,  ..., 0.9447, 0.2514, 0.8871],
        ...,
        [0.4515, 0.4020, 0.4837,  ..., 0.3970, 0.2448, 0.5362],
        [0.4191, 0.4959, 0.6645,  ..., 0.3840, 0.4717, 0.4959],
        [0.8984, 0.0059, 0.8661,  ..., 0.4371, 0.6801, 0.9837]])

Tensors placed on CPU and tensors placed on GPU are unavailable for each other:

In [0]:
a = torch.FloatTensor(10000, 10000).uniform_().cpu()
b = torch.FloatTensor(10000, 10000).uniform_().cuda()

In [0]:
a + b

RuntimeError: ignored

Example of working with GPU:

In [101]:
x = torch.FloatTensor(5, 5, 5).uniform_()

# check for CUDA availability (NVIDIA GPU)
if torch.cuda.is_available():
    # get the CUDA device name
    device = torch.device('cuda')          # CUDA-device object
    y = torch.ones_like(x, device=device)  # create a tensor on GPU
    x = x.to(device)                       # or just `.to("cuda")`
    z = x + y
    print(z)
    # you can set the type while `.to` operation
    print(z.to("cpu", torch.double))

tensor([[[1.7881, 1.2165, 1.2216, 1.7102, 1.3250],
         [1.8233, 1.7908, 1.7302, 1.5742, 1.9331],
         [1.1745, 1.7964, 1.0614, 1.9834, 1.0246],
         [1.3388, 1.9893, 1.7181, 1.0108, 1.7569],
         [1.4972, 1.0100, 1.0035, 1.5226, 1.1553]],

        [[1.7855, 1.1125, 1.1856, 1.1708, 1.6742],
         [1.0466, 1.8318, 1.0514, 1.5274, 1.9765],
         [1.2743, 1.4541, 1.0491, 1.1269, 1.5437],
         [1.3454, 1.6828, 1.0410, 1.3246, 1.2452],
         [1.1473, 1.4586, 1.2386, 1.0410, 1.4379]],

        [[1.7272, 1.0365, 1.7271, 1.0550, 1.2467],
         [1.1397, 1.7366, 1.2529, 1.1361, 1.8814],
         [1.4733, 1.6943, 1.3202, 1.7449, 1.6757],
         [1.3426, 1.8687, 1.1270, 1.1628, 1.3708],
         [1.1289, 1.2918, 1.0370, 1.4606, 1.3667]],

        [[1.6396, 1.5500, 1.3993, 1.0781, 1.4128],
         [1.6260, 1.8042, 1.9984, 1.5258, 1.6222],
         [1.4640, 1.9713, 1.2064, 1.3973, 1.7957],
         [1.1903, 1.2655, 1.1720, 1.2064, 1.5361],
         [1.0719, 1.5649,

<h3 style="text-align: center;">Autograd<b></b></h3>

The autograd package provides automatic differentiation for all operations on Tensors. It is a define-by-run framework, which means that your backprop is defined by how your code is run, and that every single iteration can be different.

The examples:

In [0]:
dtype = torch.float
device = torch.device("cuda:0")
# device = torch.device("cuda:0") # Uncomment this to run on GPU

# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 3, 3, 10

# Create random Tensors to hold input and outputs.
# Setting requires_grad=False indicates that we do not need to compute gradients
# with respect to these Tensors during the backward pass.
x = torch.randn(N, D_in, device=device, dtype=dtype)
y = torch.randn(N, D_out, device=device, dtype=dtype)

# Create random Tensors for weights.
# Setting requires_grad=True indicates that we want to compute gradients with
# respect to these Tensors during the backward pass.
w1 = torch.randn(D_in, H, device=device, dtype=dtype, requires_grad=True)
w2 = torch.randn(H, D_out, device=device, dtype=dtype, requires_grad=True)

# x = torch.FloatTensor(3, 1).uniform_()
# y = torch.FloatTensor(3, 1).uniform_()
# w = torch.FloatTensor(3, 3).uniform_() 
# b = torch.FloatTensor(3, 1).uniform_()

y_pred = (x @ w1).clamp(min=0).mm(w2)

loss = (y_pred - y).pow(2).sum()
# calculate the gradients
loss.backward()

In [103]:
print((y_pred - y).pow(2).sum())

tensor(5150.4219, device='cuda:0', grad_fn=<SumBackward0>)


In [104]:
loss.grad

/usr/local/lib/python3.6/dist-packages/torch/tensor.py:746: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  warnings.warn("The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad "


In [105]:
w1.grad

tensor([[ 1168.3838,   522.2823,  1431.5387],
        [-1481.0682,   812.2585,   893.5988],
        [-1252.0463, -1056.3475,  -571.1990]], device='cuda:0')

In [0]:
x.grad

In [0]:
y.grad

**NOTE:** the gradients are placed into the `.grad` field of tensors (variables) on which gradients were calculated. Gradients *are not placed* in the variable `loss` here!

In [108]:
w1

tensor([[ 0.6994,  0.1615,  0.7018],
        [-1.5748,  1.1088,  0.3747],
        [-1.1470, -1.6000, -0.2776]], device='cuda:0', requires_grad=True)

<h3 style="text-align: center;">Further reading:<b></b></h3>

*1). Official PyTorch tutorials: https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py*

*2). arXiv article about the deep learning frameworks comparison: https://arxiv.org/pdf/1511.06435.pdf*

*3). Useful repo with different tutorials: https://github.com/yunjey/pytorch-tutorial*

*4). Facebook AI Research (main contributor of PyTorch) website: https://facebook.ai/developers/tools*